# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 100
  - name: CV
    url: 'https://incomparable-halva-85ed56.netlify.app/Daumler_CV'
    weight: 200
  - name: TBD
    weight: 800
    identifier: TBD
  - name: Projects
    parent: TBD
    url: '/projects/'
    weight: 810
  - name: Publications
    parent: TBD
    url: '/publications/'
    weight: 820
  - name: Publications2
    parent: TBD
    url: '/publications2/'
    weight: 822
  - name: Publications3
    parent: TBD
    url: '/publications3/'
    weight: 824
  - name: Article
    parent: TBD
    url: '/article/'
    weight: 826
#  - name: Teaching
#    parent: TBD
#    url: '/talks/'
#    weight: 830
#  - name: Talks
#    parent: TBD
#    url: '/talks/slides/'
#    weight: 840
#  - name: Hobbies
#    parent: TBD #    parent: Resources
#    url: '/talks/slides/'
#    weight: 845
#  - name: About Me
#    parent: TBD
#    url: '/post/'
#    weight: 850
  - name: Test Widget
    parent: TBD
    url: '/test-widget/'
    weight: 860
  - name: View CV
    url: '/view-cv/'
    weight: 900
  - name: PSID-SHELF
#    parent: Resources
    url: 'https://www.openicpsr.org/openicpsr/project/194322'
    weight: 910
