# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 100
  - name: CV
    url: 'https://incomparable-halva-85ed56.netlify.app/Daumler_CV'
    weight: 200
#  - name: Research
#    url: '/project/'
#    weight: 310
  - name: Publications
    url: '/publications/'
    weight: 320
  - name: Test CV
    url: '/cv1/'
    weight: 400
  - name: CV1
    parent: Test CV
    url: '/cv1/'
    weight: 405
  - name: CV2
    parent: Test CV
    url: '/cv2/'
    weight: 410
  - name: CV3
    parent: Test CV
    url: '/cv3/'
    weight: 415
  - name: CV4
    parent: Test CV
    url: '/cv4/'
    weight: 420
#  - name: Teaching
#    url: '/event/'
#    weight: 330
#  - name: Resources
#  - identifier: resources
#    url: '/talks/'
#    weight: 400
#  - name: Hobbies
#    parent: Resources
#    url: '/talks/slides/'
#    weight: 410
  - name: PSID-SHELF
#    parent: Resources
    url: 'https://www.openicpsr.org/openicpsr/project/194322'
    weight: 420
#  - name: About Me
#    url: '/post/'
#    weight: 800

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
