############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: Daumler-website
  - path: blox-plugin-netlify
  - path: blox-plugin-reveal
  - path: blox-bootstrap
  - path: Daumler-website
